plugin.plugin_configuration.geolocation.map_feature.drawing:
  type: geolocation.map_feature_settings
  label: 'Common map draw settings'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        polyline:
          type: boolean
          label: 'Draw polyline'
        strokeColor:
          type: string
          label: 'strokeColor'
        strokeOpacity:
          type: string
          label: 'strokeOpacity'
        strokeWeight:
          type: string
          label: 'strokeWeight'
        geodesic:
          type: boolean
          label: 'Geodesic'
        polygon:
          type: boolean
          label: 'Draw polygon'
        fillColor:
          type: string
          label: 'fillColor'
        fillOpacity:
          type: string
          label: 'fillOpacity'

plugin.plugin_configuration.geolocation.map_feature.map_restriction:
  type: geolocation.map_feature_settings
  label: 'Map Restriction'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        north:
          type: string
          label: 'North'
        south:
          type: string
          label: 'South'
        east:
          type: string
          label: 'East'
        west:
          type: string
          label: 'West'
        strict:
          type: boolean
          label: 'strictBounds'

plugin.plugin_configuration.geolocation.map_feature.context_popup:
  type: geolocation.map_feature_settings
  label: 'Context Popup'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        content:
          type: text_format
          label: 'Content'

plugin.plugin_configuration.geolocation.map_feature.map_type_style:
  type: geolocation.map_feature_settings
  label: 'MapType Style'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        style:
          type: string
          label: 'Style'

geolocation_google_maps.map_control_feature_settings:
  type: geolocation.map_feature_settings
  label: 'Control Map Feature'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        position:
          type: string
          label: 'Position'
        behavior:
          type: string
          label: 'Behavior'

plugin.plugin_configuration.geolocation.map_feature.control_zoom:
  type: geolocation_google_maps.map_control_feature_settings
  label: 'Control Zoom'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        style:
          type: string
          label: 'Style'

plugin.plugin_configuration.geolocation.map_feature.control_rotate:
  type: geolocation_google_maps.map_control_feature_settings
  label: 'Control Rotate'

plugin.plugin_configuration.geolocation.map_feature.control_streetview:
  type: geolocation_google_maps.map_control_feature_settings
  label: 'Control Streetview'

plugin.plugin_configuration.geolocation.map_feature.control_fullscreen:
  type: geolocation_google_maps.map_control_feature_settings
  label: 'Control Fullscreen'

plugin.plugin_configuration.geolocation.map_feature.control_maptype:
  type: geolocation_google_maps.map_control_feature_settings
  label: 'Control MapType'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        style:
          type: string
          label: 'Style'

plugin.plugin_configuration.geolocation.map_feature.marker_zoom_to_animate:
  type: geolocation.map_feature_settings
  label: 'Zoom & Animate'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        marker_zoom_anchor_id:
          type: string
          label: 'Anchor'

plugin.plugin_configuration.geolocation.map_feature.geolocation_google_maps_control_directions:
  type: geolocation_google_maps.map_control_feature_settings
  label: 'Directions Control'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        origin_source:
          type: string
          label: 'Origin Source'
        origin_static_value:
          type: string
          label: 'Origin Static Value'
        destination_source:
          type: string
          label: 'Destination Source'
        destination_static_value:
          type: string
          label: 'Destination Static Value'
        travel_mode:
          type: string
          label: 'Travel Mode'
        directions_container:
          type: string
          label: 'Directions container'
        directions_container_custom_id:
          type: string
          label: 'Directions Container Custom ID'
